### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by Daantjerrr** [simgunz/anki21-addons_editor-max-image-height#3]
Hey!
I loved using this add-on, but it suddenly stopped working last week. Images appear on the cards in their original size, ignoring the max size in entered in the configuration screen. I'm on Anki version:
Version 2.1.21 (f1734a47)
Python 3.8.0 Qt 5.14.1 PyQt 5.14.1

I have tried to delete the add-on and reinstall it, but to no avail.

**Comment by simgunz** [comment]
Hi,
I just tested this on Anki 2.1.22 and it works for me on Linux.

Could you post the content of your configuration file, so I can try to replicate the problem with your configuration?

My configuration file looks like this:
```
{
    "height_or_width": "height",
    "max-height": "200px",
    "max-width": "200px"
}
```
