### ISSUE TITLE
Update needed for Anki 2.1.41+

### ISSUE THREAD

**Issue by amazeum** [simgunz/anki21-addons_editor-max-image-height#4]
Hi, I love this add-on and noticed that it is no longer working for Anki 2.1.41. Damien said that the Javascript and HTML have been reworked for the editor so I imagine that is why the add-on is not functioning. Hopefully updating it is an easy fix. I don't have any Python or HTML coding experience but know someone who does so if I figure out how to get the add-on running I'll post it here. Thanks for your work on this add-on! It definitely makes Anki easier to use.

**Comment by simgunz** [comment]
I'll try to update the addon soon.

**Comment by NeoMD96** [comment]
Hope you can update this for 2.41 soon man. 
Love this addon.

**Comment by amazeum** [comment]
@NeoMD96 As a temporary fix I found that on 2.1.42 adding the code `anki-editable img{max-height:___px}` (or `max-width` if that's what you prefer) to the file /Applications/Anki.app/Contents/Resources/aqt_data/web/css/editable.css will constrain the image size in the editor. Not a solution to the add-on itself but I feel it's worth sharing here for anyone who checks this thread
